apiVersion: batch/v1
kind: Job
metadata:
  name: pulsar-topics
  namespace: nalej
  labels:
    app: pulsar
    component: nalej-bus
    cluster: management
spec:
  template:
    spec:
      containers:
        - name: pulsar-topics
          image: apachepulsar/pulsar:2.3.1
          command: ["sh", "-c"]
          args:
            - >
              bin/pulsar-admin --admin-url http://broker.nalej.svc:8080 tenants create nalej &&
              bin/pulsar-admin --admin-url http://broker.nalej.svc:8080 namespaces create management || true;
      restartPolicy: OnFailure