apiVersion: v1
kind: Service
metadata:
  name: bookie
  namespace: __NPH_NAMESPACE
  labels:
    app: bookie
    component: nalej-bus
    cluster: management
spec:
  ports:
    - port: 3181
      name: server
  type: ClusterIP
  selector:
    app: bookie
    component: nalej-bus
    cluster: management