apiVersion: v1
kind: Service
metadata:
  name: bookkeeper
  namespace: nalej
  labels:
    app: bookie
    component: nalej-bus
    cluster: management
spec:
  ports:
    - port: 3181
      name: server
  clusterIP: None
  selector:
    app: bookie
    component: nalej-bus
    cluster: management